#!/bin/bash
apt-get update
apt-get install -y nginx
cp /etc/nginx/sites-available/default{,bak} && sed -i '/listen 80;/c\    listen 80;' /etc/nginx/sites-available/default && service nginx restart
service nginx status | grep -q "not running" && echo " * nginx is not running" || echo " * nginx is running"
