#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Use scp to transfer the file to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username"@"$server_ip":~

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer completed successfully."
else
    echo "File transfer failed."
fi

